# Generated by Django 5.1.6 on 2025-02-13 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endPoint', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuLoad', models.FloatField()),
                ('memLoad', models.FloatField()),
                ('diskLoad', models.FloatField()),
                ('upTime', models.DurationField()),
                ('сurrentTime', models.DateTimeField()),
                ('serverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoring.server')),
            ],
        ),
    ]
