# Generated by Django 5.1.6 on 2025-02-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverstat',
            old_name='сurrentTime',
            new_name='currentTime',
        ),
        migrations.AddField(
            model_name='server',
            name='cpulimit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='disklimit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='memlimit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WarningStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuLoad', models.FloatField()),
                ('memLoad', models.FloatField()),
                ('diskLoad', models.FloatField()),
                ('upTime', models.DurationField()),
                ('currentTime', models.DateTimeField()),
                ('serverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monitoring.server')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
