# Generated by Django 5.1.6 on 2025-02-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0002_rename_сurrenttime_serverstat_currenttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cputimelimit',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='server',
            name='disktimelimit',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='server',
            name='memtimelimit',
            field=models.IntegerField(default=15),
        ),
    ]
