# Generated by Django 5.1.6 on 2025-02-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0003_server_cputimelimit_server_disktimelimit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='maxtimeout',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
