# Generated by Django 5.1.6 on 2025-02-21 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0004_server_maxtimeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='maxtimeout',
            field=models.DurationField(verbose_name=datetime.timedelta(seconds=3600)),
        ),
    ]
