# Generated by Django 5.1.6 on 2025-02-21 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoring', '0005_alter_server_maxtimeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningstat',
            name='servershutdown',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
